name = "Danny's Modpack"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5b9b48349ce1667ef54c10afa06917aad8d585cb67c0e639650cc01434d6b578"

[versions]
fabric = "0.15.3"
minecraft = "1.20.1"
