name = "Danny's Modpack"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6098782ef873fe62f3f5991bfefbf9ddf1f19f95008c1673319c11f0c8765fe4"

[versions]
fabric = "0.15.3"
minecraft = "1.20.1"
