name = "Danny's Modpack"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9f8c779afe97fdb083b935bc531978aa49b6b2e13496ad7800d7fad34d99a3cb"

[versions]
fabric = "0.14.3"
minecraft = "1.18.2"
