name = "Danny's Modpack"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "90084c8f24025ce2fea210cb88d5f5b55c076a14b8f708a9e608b01bff070016"

[versions]
fabric = "0.15.3"
minecraft = "1.20.1"
