name = "Danny's Modpack"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ca9f661bec348a822ddca788d31e726b8d3b5ff08075cab71b26b423ae0b831f"

[versions]
fabric = "0.14.3"
minecraft = "1.18.2"
