name = "Danny's Modpack"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "847aa3a4561c3450329947917955afd436ae0b23d19ecc9733dabcdeb0aa8668"

[versions]
fabric = "0.14.3"
minecraft = "1.18.2"
