name = "Danny's Modpack"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9fd3e2631a3efb385e149e717c8a43b0544ecf8641fee10f50d12c022a8ea8c6"

[versions]
fabric = "0.14.3"
minecraft = "1.18.2"
