name = "Danny's Modpack"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8749f50e3e0ed814abfafd3f641fb5c3240658738b408d05e011706b5ac82623"

[versions]
fabric = "0.15.3"
minecraft = "1.20.1"
