name = "Danny's Modpack"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c8dbdfe52da2738420dbb4676ef74856bc3efb3f2cb3b1462c253d157d413813"

[versions]
fabric = "0.14.3"
minecraft = "1.18.2"
