name = "Danny's Modpack"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e1c740f4f32b59a148c5f95b147586e90f9d44e497194ac9ca2f9a13792b3e10"

[versions]
fabric = "0.15.3"
minecraft = "1.20.1"
