name = "Danny's Modpack"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fb3f088568bc9df79fa7e2a76487a53e0d6fcbb6b44ac218b37023d9ebd0599b"

[versions]
fabric = "0.15.3"
minecraft = "1.20.1"
