name = "Danny's Modpack"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e6b781ec907cde467b39f2d0107949a331725c5fdc8dd441d8cc31ed47b5c275"

[versions]
fabric = "0.14.3"
minecraft = "1.18.2"
