name = "Danny's Modpack"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "26e17a81f12dfc141e71eb4c1ca68c47ec43efa61c7eb4cf61e5d52ef14cf5ac"

[versions]
fabric = "0.15.3"
minecraft = "1.20.1"
