name = "Danny's Modpack"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "50b9c568233275ad62de650eab336a4cc967c89f869d69d59a0495f6483a6bfc"

[versions]
fabric = "0.14.3"
minecraft = "1.18.2"
