name = "Danny's Modpack"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b24ca1ac0049fd059ad2afbc5038ded15182ade94bd420a9c91b855ddc9d416d"

[versions]
fabric = "0.14.3"
minecraft = "1.18.2"
