name = "Danny's Modpack"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cbfe6e45483c0e375f19a1ace63339fbfa54d7a96e9f74e331d62799eb80bc0e"

[versions]
fabric = "0.15.3"
minecraft = "1.20.1"
