name = "Additional Structures (Fabric)"
filename = "AdditionalStructures-1.18.2-(v.3.0.3).jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3740/439/AdditionalStructures-1.18.2-(v.3.0.3).jar"
hash-format = "sha1"
hash = "61ec06547bb2001559f668bcc9dc820a7a8d1efb"

[update]
[update.curseforge]
file-id = 3740439
project-id = 585782
