name = "AttributeFix"
filename = "AttributeFix-Fabric-1.18.2-14.0.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3683/608/AttributeFix-Fabric-1.18.2-14.0.1.jar"
hash-format = "sha1"
hash = "a892121eaeec3e1daa3531fffb3fbcf5b34f926d"

[update]
[update.curseforge]
file-id = 3683608
project-id = 280510
