name = "BetterNether"
filename = "better-nether-6.1.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3772/61/better-nether-6.1.1.jar"
hash-format = "sha1"
hash = "5387b9bf39a6ca095e57aff9833a46ce7d692726"

[update]
[update.curseforge]
file-id = 3772061
project-id = 311377
