name = "Bosses of Mass Destruction"
filename = "BOMD-1.3.6-1.18.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3695/22/BOMD-1.3.6-1.18.2.jar"
hash-format = "sha1"
hash = "a28b8df1285b617e2d47fa90bbcf573fb423f228"

[update]
[update.curseforge]
file-id = 3695022
project-id = 438365
