name = "Falling Leaves (Fabric)"
filename = "fallingleaves-1.11.1+1.18.2.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3782/712/fallingleaves-1.11.1+1.18.2.jar"
hash-format = "sha1"
hash = "eaedf924b6774ef266ca0382d38c6325aa37f331"

[update]
[update.curseforge]
file-id = 3782712
project-id = 417510
