name = "Illager Expansion [Fabric]"
filename = "illager_expansion-0.1.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3749/152/illager_expansion-0.1.5.jar"
hash-format = "sha1"
hash = "b40d6b158baa71a59bc452365cd533384dde29ba"

[update]
[update.curseforge]
file-id = 3749152
project-id = 597284
