name = "More Villagers [Fabric]"
filename = "morevillagers-FABRIC-1.18.2-3.2.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3699/183/morevillagers-FABRIC-1.18.2-3.2.0.jar"
hash-format = "sha1"
hash = "cb535a7d0949495ebfcb14df91dd94886e56b848"

[update]
[update.curseforge]
file-id = 3699183
project-id = 486080
