name = "Motschen's Better Leaves"
filename = "Better-Leaves-7.2-1.19+.zip"
side = "both"

[download]
hash-format = "sha1"
hash = "83aabd3589433b6d1793900efd2f35fe22ba326f"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 4434043
project-id = 380969
