name = "Motschen's Better Leaves"
filename = "Better-Leaves-6.2-1.13+.zip"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3759/621/Better-Leaves-6.2-1.13+.zip"
hash-format = "sha1"
hash = "0f901f13e0d07deec6cb19d8cba6ee50d4b43bfa"

[update]
[update.curseforge]
file-id = 3759621
project-id = 380969
