name = "Oh The Biomes You'll Go Refabricated"
filename = "Oh_The_Biomes_You'll_Go-fabric-1.18.2-1.4-RC-11.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3775/364/Oh_The_Biomes_You'll_Go-fabric-1.18.2-1.4-RC-11.jar"
hash-format = "sha1"
hash = "556bcf7cb7702ebc9d55b510e4697b39be25ae01"

[update]
[update.curseforge]
file-id = 3775364
project-id = 391378
