name = "Oh The Biomes You'll Go Refabricated"
filename = "Oh_The_Biomes_You'll_Go-fabric-1.18.2-1.4-RC-22.jar"
side = "both"

[download]
hash-format = "sha1"
hash = "d120d64471a2bbd40d60507eb8993c21f3e2244a"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 3811456
project-id = 391378
