name = "Repurposed Structures (Quilt/Fabric)"
filename = "repurposed_structures-7.1.11+1.20.1-fabric.jar"
side = "both"

[download]
hash-format = "sha1"
hash = "8025c07c711496b5303c92d881cdaea47f60d33d"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 4823484
project-id = 391366
