name = "Stoneholm, Underground Villages (Fabric)"
filename = "stoneholm-1.4.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3736/161/stoneholm-1.4.3.jar"
hash-format = "sha1"
hash = "bf648ddb79ec7b49fcd4532ebb9189b092258a5b"

[update]
[update.curseforge]
file-id = 3736161
project-id = 460336
