name = "TerraBlender (Fabric)"
filename = "TerraBlender-fabric-1.18.2-1.1.0.101.jar"
side = "both"

[download]
hash-format = "sha1"
hash = "cda21674294abea7bcac6f60b7b83e382c9b2de6"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 3801032
project-id = 565956
